application: yafra
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
- url: /_ah/login_required
  script: main.app
- url: /admin
  script: main.app
  login: admin
- url: /admin/.*
  script: main.app
  login: admin
- url: /cron/.*
  script: main.app
  login: admin
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: webapp2
  version: latest
- name: PIL
  version: latest

builtins:
- remote_api: on
